import React from 'react';
import { Table, Download, FileSpreadsheet, Check } from 'lucide-react';

export default function ForecastTable({ forecastData, selectedModel, datasetName }) {
  if (!forecastData || forecastData.length === 0) return null;

  const handleExportCSV = () => {
    const headers = ['step_ahead', 'timestamp', 'predicted_consumption'];
    const rows = forecastData.map((d) => [
      d.step_ahead,
      d.timestamp,
      d.predicted_consumption ?? d.forecast_consumption,
    ]);

    const csvContent =
      'data:text/csv;charset=utf-8,' +
      [headers.join(','), ...rows.map((e) => e.join(','))].join('\n');

    const encodedUri = encodeURI(csvContent);
    const link = document.createElement('a');
    link.setAttribute('href', encodedUri);
    link.setAttribute('download', `energy_forecast_${datasetName || 'results'}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="glass-card" style={{ padding: '24px', marginBottom: '32px' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '18px', flexWrap: 'wrap', gap: '12px' }}>
        <div>
          <h3 style={{ fontSize: '1.05rem', fontWeight: 600, display: 'flex', alignItems: 'center', gap: '8px' }}>
            <Table size={18} color="#06b6d4" />
            3. Step-by-Step Forecast Points
          </h3>
          <p style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>
            Sequential multi-step points generated by {selectedModel}
          </p>
        </div>

        <button className="btn-secondary" onClick={handleExportCSV}>
          <Download size={15} color="#38bdf8" />
          Export Forecast CSV
        </button>
      </div>

      <div style={{ maxHeight: '340px', overflowY: 'auto', border: '1px solid var(--border-color)', borderRadius: 'var(--radius-sm)' }}>
        <table style={{ width: '100%', borderCollapse: 'collapse', textAlign: 'left', fontSize: '0.85rem' }}>
          <thead style={{ position: 'sticky', top: 0, background: '#11192e', borderBottom: '1px solid var(--border-color)', zIndex: 10 }}>
            <tr style={{ color: 'var(--text-dim)', fontSize: '0.75rem', textTransform: 'uppercase' }}>
              <th style={{ padding: '10px 16px' }}>Step Ahead</th>
              <th style={{ padding: '10px 16px' }}>Future Timestamp</th>
              <th style={{ padding: '10px 16px' }}>Predicted Consumption</th>
            </tr>
          </thead>
          <tbody>
            {forecastData.map((pt, idx) => (
              <tr
                key={idx}
                style={{
                  borderBottom: '1px solid rgba(255, 255, 255, 0.03)',
                  background: idx % 2 === 0 ? 'rgba(255, 255, 255, 0.01)' : 'transparent',
                }}
              >
                <td style={{ padding: '10px 16px', fontWeight: 600, color: '#38bdf8' }}>
                  +{pt.step_ahead}
                </td>
                <td style={{ padding: '10px 16px', color: 'var(--text-main)' }}>
                  {pt.timestamp}
                </td>
                <td style={{ padding: '10px 16px', fontWeight: 600, color: '#34d399' }}>
                  {(pt.predicted_consumption ?? pt.forecast_consumption)?.toFixed(4)}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
